services:
  frontend:
    image: nginx:alpine
    ports:
      - 8090:8090
    volumes:
      - ./frontend:/usr/share/nginx/html

  backend:
    image: demo-microservice
    platform: wasi/wasm32
    build:
      context: backend/
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: mysql://root:whalehello@db:3306/mysql
      RUST_BACKTRACE: full
    restart: unless-stopped
    runtime: io.containerd.wasmedge.v1

  db:
    image: mariadb:10.9
    environment:
      MYSQL_ROOT_PASSWORD: whalehello
